import { layout, pageIntro, button, finalCta } from './components.mjs';
import { localQuestions } from './local.mjs';

export function regionalPage() {
  return layout({path:'/regiao-presidente-prudente/',title:'Atendimento regional | Presidente Prudente e até 200 km',description:'Marketing digital para empresas de Presidente Prudente e municípios em até 200 km. Conheça o atendimento, os serviços e como começar com Tony Ananias.',body:`${pageIntro('Marketing para empresas<br>de Presidente Prudente e região.','Atendimento a negócios da cidade e de municípios em um raio de até 200 km, com estratégia de anúncios, SEO local, mensuração e automação.','<span>Atendimento regional</span>')}
  <section class="section container service-question"><h2>O alcance da campanha começa na área que você atende.</h2><div><p>Uma empresa que recebe clientes no endereço comercial tem necessidades diferentes de quem faz entregas, visitas ou vendas online. Antes de definir canais e investimento, a conversa precisa esclarecer onde estão os clientes que sua equipe consegue atender.</p><p>A TA Consulting tem base em Presidente Prudente. O foco regional de até 200 km orienta nosso atendimento; a área de cada campanha é definida de acordo com a operação do cliente e as possibilidades da plataforma.</p></div></section>
  <section class="section detail-scope"><div class="container"><div class="section-heading"><h2>O que precisamos entender<br>sobre a sua empresa.</h2><p>Essas informações ajudam a definir um projeto adequado ao cenário local.</p></div><div class="scope-list"><article><h3>Cidade e área de atendimento</h3><p>Onde a empresa está, quais localidades atende e se existem limites de entrega, deslocamento ou disponibilidade.</p></article><article><h3>Oferta e perfil de cliente</h3><p>O produto ou serviço prioritário, quem decide a compra e o que essa pessoa precisa saber antes de entrar em contato.</p></article><article><h3>Canais e histórico</h3><p>Site, redes sociais, presença no Google e campanhas que já foram realizadas. A análise considera o que pode ser aproveitado.</p></article><article><h3>Atendimento e investimento</h3><p>Quem recebe os contatos, como acompanha as oportunidades e qual investimento a empresa consegue manter enquanto aprende com os dados.</p></article></div></div></section>
  <section class="section container faq-section"><h2>Um caminho para cada necessidade.</h2><div><h3>Quero gerar contatos com anúncios</h3><p>O trabalho de tráfego pago conecta escolha de canais, mensagens e páginas de destino à mensuração dos contatos.</p>${button('Gestão de tráfego pago','/trafego-pago/',true)}<h3>Quero melhorar minha presença no Google</h3><p>SEO local organiza informações e conteúdo para quem pesquisa produtos e serviços da empresa na região.</p>${button('SEO local e presença no Google','/seo-local/',true)}<h3>Preciso organizar as oportunidades</h3><p>CRM e automação ajudam a manter o contexto entre a origem do contato e a equipe que conduz o atendimento.</p>${button('WhatsApp, CRM e automação','/automacao/',true)}</div></section>
  ${localQuestions()}${finalCta()}`});
}
